#pragma config(Sensor, S2,     ,               sensorEV3_Gyro)
#pragma config(Sensor, S4,     ,               sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////////////////////
// ROBOTC EV3 remote control demonstration program.
// This program receives messages from the host computer: Forward, Backward, Left and Right.
// It sends back the distance in cm measured by the ultrasonic sensor and the angle in degrees
// measured by the gyro sensor.
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
// Connection scheme:
// motorA: medium motor front lever
// motorB: large motor right wheel
// motorC: large motor left wheel
// motorD: -
// Sensor S1: Touch sensor
// Sensor S2: Gyro sensor
// Sensor S3: Color sensor
// Sensor S4: Ultrasonic sensor
////////////////////////////////////////////////////////////////////////////////


// EV3Mailbox.c is needed to enable sending and receiving mailbox messages.
// It is possible to have ten input mailboxes and one output mailbox.
// However in the below code only EV3_INBOX0 and EV3_OUTBOX0 are used.
// See the comments in EV3Mailbox.c for additional info.
// Unfortunately ROBOTC cannot handle multipe C files so we have to include it.
#include "EV3Mailbox.c"


task main()
{
	displayBigTextLine(0, "Started!");

	char msgBufIn[20];  // To contain the incoming message.
	char msgBufOut[20];  // To contain the outgoing message
	string IncomingMessage; //To contain the string of the incoming message
	bool ride;

	openMailboxIn("EV3_INBOX0");
	openMailboxOut("EV3_OUTBOX0");

	while (true)
	{
		// Read input message.
		// readMailboxIn() is non-blocking and returns "" if there is no message.
		readMailboxIn("EV3_INBOX0", msgBufIn);
		if (strcmp(msgBufIn, "") != 0)
		{
			stringFromChars(IncomingMessage,msgBufIn) ;
			if (IncomingMessage == "Forward")
			{
				setMotorSyncEncoder(motorB,motorC,0,360,20);
				displayBigTextLine(8,IncomingMessage);
				delay(500);
			}
			else if (IncomingMessage == "Backward")
			{
				setMotorSyncEncoder(motorB,motorC,0,360,-20);
				displayBigTextLine(8,IncomingMessage);
				delay(500);
			}
			else if (IncomingMessage == "Left")
			{

				setMotorSyncEncoder(motorB,motorC,100,450,20);
				delay(1000);

			}
			else if (IncomingMessage == "Right")		{

				setMotorSyncEncoder(motorB,motorC,-100,450,20);
			}
			else if (IncomingMessage == "Happy")
			{

			drawBmpfile(0, 127, "Big smile");
			delay(2000);
			eraseDisplay();






			}
			else if(IncomingMessage == "Nathan")

			{
				motor[motorA] = 20;
			  drawBmpfile(0, 127, "Angry");
				delay(2000);
			}


			else if (IncomingMessage == "Lijn")
			{
				ride = false;
				while ( ride == false)
				{
					while(getColorReflected(S3) < 45)
					{
						setMotorSync(motorB, motorC, 0, 20);


					}
					while(getColorReflected(S3) >= 45)
					{
						setMotorSync(motorB, motorC, 10, 20);
					}
				}
			}


			// Here fill your incoming message handling.
			// For example when message "Forward" is received, the EV3 should move forward.

		}
		else
		{
			displayBigTextLine(8, "Empty message!");
		}



		// Here fill your outgoing message handling.
		// This means sending the distance in cm measured by the ultrasonic sensor
		// and the angle in degrees measured by the gyro sensor.
		// Put both values in msgBufOut.
		// Use the format ?<distance> <angle>" (space between distance and angle) so that it can be read by the host program.









		delay(1000);  // Wait 100 ms to give host computer time to react.
	}
	closeMailboxIn("EV3_INBOX0");
	closeMailboxOut("EV3_OUTBOX0");
	return;
}
